name: Cypress tests
on:
  - push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        browser: ['chrome', 'firefox']
    name: Run Cypress tests on ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          headed: true
          browser: ${{ matrix.browser }}
          record: false
  release:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
